package com.test.vo;

import com.test.model.Testcase;

public class CaseVo extends Testcase {
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getMethod() {
		return method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getProjectname() {
		return projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}

	//获得接口的
	  private String name;
	  
	  private String interfaceid;

	    public String getInterfaceid() {
		return interfaceid;
	}

	public void setInterfaceid(String interfaceid) {
		this.interfaceid = interfaceid;
	}

		/**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column apinfor.URL
	     *
	     * @mbggenerated Mon May 29 11:09:11 CST 2017
	     */
	    private String url;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column apinfor.method
	     *
	     * @mbggenerated Mon May 29 11:09:11 CST 2017
	     */
	    private String method;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column apinfor.projectname
	     *
	     * @mbggenerated Mon May 29 11:09:11 CST 2017
	     */
	    private String projectname;

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column apinfor.id
	     *
	     * @return the value of apinfor.id
	     *
	     * @mbggenerated Mon May 29 11:09:11 CST 2017
	     */ 

}
