package com.test.model;

public class Apinfor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apinfor.id
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apinfor.name
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apinfor.URL
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apinfor.method
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apinfor.projectname
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    private String projectname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apinfor.id
     *
     * @return the value of apinfor.id
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apinfor.id
     *
     * @param id the value for apinfor.id
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apinfor.name
     *
     * @return the value of apinfor.name
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apinfor.name
     *
     * @param name the value for apinfor.name
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apinfor.URL
     *
     * @return the value of apinfor.URL
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apinfor.URL
     *
     * @param url the value for apinfor.URL
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apinfor.method
     *
     * @return the value of apinfor.method
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apinfor.method
     *
     * @param method the value for apinfor.method
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apinfor.projectname
     *
     * @return the value of apinfor.projectname
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apinfor.projectname
     *
     * @param projectname the value for apinfor.projectname
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }
}