package com.test.model;

public class Caseresult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caseresult.id
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caseresult.response
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caseresult.caseid
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String caseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caseresult.dsc
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String dsc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caseresult.id
     *
     * @return the value of caseresult.id
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caseresult.id
     *
     * @param id the value for caseresult.id
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caseresult.response
     *
     * @return the value of caseresult.response
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caseresult.response
     *
     * @param response the value for caseresult.response
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caseresult.caseid
     *
     * @return the value of caseresult.caseid
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getCaseid() {
        return caseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caseresult.caseid
     *
     * @param caseid the value for caseresult.caseid
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setCaseid(String caseid) {
        this.caseid = caseid == null ? null : caseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caseresult.dsc
     *
     * @return the value of caseresult.dsc
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caseresult.dsc
     *
     * @param dsc the value for caseresult.dsc
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setDsc(String dsc) {
        this.dsc = dsc == null ? null : dsc.trim();
    }
}