package com.test.model;

import java.util.Date;

public class Reporter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.id
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.excdate
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private Date excdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.totaltime
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private String totaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.totalcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private Integer totalcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.successcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private Integer successcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.failurescount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private Integer failurescount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.skipscount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private Integer skipscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.errorcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private Integer errorcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.successpercent
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private Double successpercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reporter.text
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.id
     *
     * @return the value of reporter.id
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.id
     *
     * @param id the value for reporter.id
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.excdate
     *
     * @return the value of reporter.excdate
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public Date getExcdate() {
        return excdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.excdate
     *
     * @param excdate the value for reporter.excdate
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setExcdate(Date excdate) {
        this.excdate = excdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.totaltime
     *
     * @return the value of reporter.totaltime
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public String getTotaltime() {
        return totaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.totaltime
     *
     * @param totaltime the value for reporter.totaltime
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setTotaltime(String totaltime) {
        this.totaltime = totaltime == null ? null : totaltime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.totalcount
     *
     * @return the value of reporter.totalcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public Integer getTotalcount() {
        return totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.totalcount
     *
     * @param totalcount the value for reporter.totalcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setTotalcount(Integer totalcount) {
        this.totalcount = totalcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.successcount
     *
     * @return the value of reporter.successcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public Integer getSuccesscount() {
        return successcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.successcount
     *
     * @param successcount the value for reporter.successcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setSuccesscount(Integer successcount) {
        this.successcount = successcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.failurescount
     *
     * @return the value of reporter.failurescount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public Integer getFailurescount() {
        return failurescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.failurescount
     *
     * @param failurescount the value for reporter.failurescount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setFailurescount(Integer failurescount) {
        this.failurescount = failurescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.skipscount
     *
     * @return the value of reporter.skipscount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public Integer getSkipscount() {
        return skipscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.skipscount
     *
     * @param skipscount the value for reporter.skipscount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setSkipscount(Integer skipscount) {
        this.skipscount = skipscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.errorcount
     *
     * @return the value of reporter.errorcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public Integer getErrorcount() {
        return errorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.errorcount
     *
     * @param errorcount the value for reporter.errorcount
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setErrorcount(Integer errorcount) {
        this.errorcount = errorcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.successpercent
     *
     * @return the value of reporter.successpercent
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public Double getSuccesspercent() {
        return successpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.successpercent
     *
     * @param successpercent the value for reporter.successpercent
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setSuccesspercent(Double successpercent) {
        this.successpercent = successpercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reporter.text
     *
     * @return the value of reporter.text
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reporter.text
     *
     * @param text the value for reporter.text
     *
     * @mbggenerated Sun Jul 16 11:16:31 CST 2017
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}