package com.test.model;

public class Testcase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.id
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.casename
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String casename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.scenario
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String scenario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.parmater
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String parmater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.expect
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    private String expect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.id
     *
     * @return the value of testcase.id
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.id
     *
     * @param id the value for testcase.id
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.casename
     *
     * @return the value of testcase.casename
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getCasename() {
        return casename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.casename
     *
     * @param casename the value for testcase.casename
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setCasename(String casename) {
        this.casename = casename == null ? null : casename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.scenario
     *
     * @return the value of testcase.scenario
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getScenario() {
        return scenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.scenario
     *
     * @param scenario the value for testcase.scenario
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setScenario(String scenario) {
        this.scenario = scenario == null ? null : scenario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.parmater
     *
     * @return the value of testcase.parmater
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getParmater() {
        return parmater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.parmater
     *
     * @param parmater the value for testcase.parmater
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setParmater(String parmater) {
        this.parmater = parmater == null ? null : parmater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.expect
     *
     * @return the value of testcase.expect
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public String getExpect() {
        return expect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.expect
     *
     * @param expect the value for testcase.expect
     *
     * @mbggenerated Mon Jun 12 17:27:06 CST 2017
     */
    public void setExpect(String expect) {
        this.expect = expect == null ? null : expect.trim();
    }
}