package com.test.model;

public class Testcase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.id
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.casename
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String casename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.scenario
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String scenario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.parmater
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String parmater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.apiid
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String apiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.expectkey1
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String expectkey1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.expectvalue1
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String expectvalue1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.expectkey2
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String expectkey2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testcase.expectvalue2
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    private String expectvalue2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.id
     *
     * @return the value of testcase.id
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.id
     *
     * @param id the value for testcase.id
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.casename
     *
     * @return the value of testcase.casename
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getCasename() {
        return casename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.casename
     *
     * @param casename the value for testcase.casename
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setCasename(String casename) {
        this.casename = casename == null ? null : casename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.scenario
     *
     * @return the value of testcase.scenario
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getScenario() {
        return scenario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.scenario
     *
     * @param scenario the value for testcase.scenario
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setScenario(String scenario) {
        this.scenario = scenario == null ? null : scenario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.parmater
     *
     * @return the value of testcase.parmater
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getParmater() {
        return parmater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.parmater
     *
     * @param parmater the value for testcase.parmater
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setParmater(String parmater) {
        this.parmater = parmater == null ? null : parmater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.apiid
     *
     * @return the value of testcase.apiid
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getApiid() {
        return apiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.apiid
     *
     * @param apiid the value for testcase.apiid
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setApiid(String apiid) {
        this.apiid = apiid == null ? null : apiid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.expectkey1
     *
     * @return the value of testcase.expectkey1
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getExpectkey1() {
        return expectkey1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.expectkey1
     *
     * @param expectkey1 the value for testcase.expectkey1
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setExpectkey1(String expectkey1) {
        this.expectkey1 = expectkey1 == null ? null : expectkey1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.expectvalue1
     *
     * @return the value of testcase.expectvalue1
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getExpectvalue1() {
        return expectvalue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.expectvalue1
     *
     * @param expectvalue1 the value for testcase.expectvalue1
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setExpectvalue1(String expectvalue1) {
        this.expectvalue1 = expectvalue1 == null ? null : expectvalue1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.expectkey2
     *
     * @return the value of testcase.expectkey2
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getExpectkey2() {
        return expectkey2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.expectkey2
     *
     * @param expectkey2 the value for testcase.expectkey2
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setExpectkey2(String expectkey2) {
        this.expectkey2 = expectkey2 == null ? null : expectkey2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testcase.expectvalue2
     *
     * @return the value of testcase.expectvalue2
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public String getExpectvalue2() {
        return expectvalue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testcase.expectvalue2
     *
     * @param expectvalue2 the value for testcase.expectvalue2
     *
     * @mbggenerated Wed Jul 12 15:05:45 CST 2017
     */
    public void setExpectvalue2(String expectvalue2) {
        this.expectvalue2 = expectvalue2 == null ? null : expectvalue2.trim();
    }
}