package com.test.dao;

import com.test.model.Apinfor;
import com.test.model.ApinforExample;
import com.test.model.User;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ApinforMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @SelectProvider(type=ApinforSqlProvider.class, method="countByExample")
    int countByExample(ApinforExample example);
    
    
    
    @Select({
    	"select *",
        "from apinfor"
    })
    List<Apinfor> AllApinfor();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @DeleteProvider(type=ApinforSqlProvider.class, method="deleteByExample")
    int deleteByExample(ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @Delete({
        "delete from apinfor",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @Insert({
        "insert into apinfor (id, name, ",
        "URL, method, projectname)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{method,jdbcType=VARCHAR}, #{projectname,jdbcType=VARCHAR})"
    })
    int insert(Apinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @InsertProvider(type=ApinforSqlProvider.class, method="insertSelective")
    int insertSelective(Apinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @SelectProvider(type=ApinforSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="method", property="method", jdbcType=JdbcType.VARCHAR),
        @Result(column="projectname", property="projectname", jdbcType=JdbcType.VARCHAR)
    })
    List<Apinfor> selectByExample(ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @Select({
        "select",
        "id, name, URL, method, projectname",
        "from apinfor",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="method", property="method", jdbcType=JdbcType.VARCHAR),
        @Result(column="projectname", property="projectname", jdbcType=JdbcType.VARCHAR)
    })
    Apinfor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @UpdateProvider(type=ApinforSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Apinfor record, @Param("example") ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @UpdateProvider(type=ApinforSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Apinfor record, @Param("example") ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @UpdateProvider(type=ApinforSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Apinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Mon May 29 11:09:11 CST 2017
     */
    @Update({
        "update apinfor",
        "set name = #{name,jdbcType=VARCHAR},",
          "URL = #{url,jdbcType=VARCHAR},",
          "method = #{method,jdbcType=VARCHAR},",
          "projectname = #{projectname,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Apinfor record);
}