package com.test.dao;

import com.test.model.Apinfor;
import com.test.model.ApinforExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ApinforMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Fri May 26 10:54:40 CST 2017
     */
    @SelectProvider(type=ApinforSqlProvider.class, method="countByExample")
    int countByExample(ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Fri May 26 10:54:40 CST 2017
     */
    @DeleteProvider(type=ApinforSqlProvider.class, method="deleteByExample")
    int deleteByExample(ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Fri May 26 10:54:40 CST 2017
     */
    @Insert({
        "insert into apinfor (id, name, ",
        "URL, method, projectname)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{method,jdbcType=VARCHAR}, #{projectname,jdbcType=VARCHAR})"
    })
    int insert(Apinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Fri May 26 10:54:40 CST 2017
     */
    @InsertProvider(type=ApinforSqlProvider.class, method="insertSelective")
    int insertSelective(Apinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Fri May 26 10:54:40 CST 2017
     */
    @SelectProvider(type=ApinforSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="method", property="method", jdbcType=JdbcType.VARCHAR),
        @Result(column="projectname", property="projectname", jdbcType=JdbcType.VARCHAR)
    })
    List<Apinfor> selectByExample(ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Fri May 26 10:54:40 CST 2017
     */
    @UpdateProvider(type=ApinforSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Apinfor record, @Param("example") ApinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apinfor
     *
     * @mbggenerated Fri May 26 10:54:40 CST 2017
     */
    @UpdateProvider(type=ApinforSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Apinfor record, @Param("example") ApinforExample example);
}